magick convert fh-01a-snow.png  -compose copy -bordercolor transparent -border 5 temp/fh-01a-snow.png
magick convert fh-01b-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-01b-metal.png
magick convert fh-01c-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-01c-snow.png
magick convert fh-01d-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-01d-metal.png
magick convert fh-01e-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-01e-snow.png
magick convert fh-01f-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-01f-cave.png
magick convert fh-01g-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-01g-snow.png
magick convert fh-01h-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-01h-dungeon.png
magick convert fh-02a-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-02a-dungeon.png
magick convert fh-02b-wood.png -compose copy -bordercolor transparent -border 5 temp/fh-02b-wood.png
magick convert fh-02c-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-02c-dungeon.png
magick convert fh-02d-wood.png -compose copy -bordercolor transparent -border 5 temp/fh-02d-wood.png
magick convert fh-02e-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-02e-snow.png
magick convert fh-02f-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-02f-metal.png
magick convert fh-02g-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-02g-snow.png
magick convert fh-02h-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-02h-metal.png
magick convert fh-02i-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-02i-dungeon.png
magick convert fh-02j-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-02j-cave.png
magick convert fh-02k-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-02k-dungeon.png
magick convert fh-02l-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-02l-cave.png
magick convert fh-03a-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-03a-cave.png
magick convert fh-03b-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-03b-metal.png
magick convert fh-03c-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-03c-dungeon.png
magick convert fh-03d-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-03d-snow.png
magick convert fh-04a-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-04a-cave.png
magick convert fh-04b-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-04b-metal.png
magick convert fh-04c-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-04c-snow.png
magick convert fh-04d-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-04d-dungeon.png
magick convert fh-05a-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-05a-cave.png
magick convert fh-05b-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-05b-snow.png
magick convert fh-06a-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-06a-snow.png
magick convert fh-06b-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-06b-metal.png
magick convert fh-07a-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-07a-cave.png
magick convert fh-07b-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-07b-snow.png
magick convert fh-07c-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-07c-cave.png
magick convert fh-07d-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-07d-snow.png
magick convert fh-07e-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-07e-dungeon.png
magick convert fh-07f-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-07f-metal.png
magick convert fh-07g-wood.png -compose copy -bordercolor transparent -border 5 temp/fh-07g-wood.png
magick convert fh-07h-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-07h-metal.png
magick convert fh-08a-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-08a-metal.png
magick convert fh-08b-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-08b-cave.png
magick convert fh-09a-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-09a-snow.png
magick convert fh-09b-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-09b-dungeon.png
magick convert fh-09c-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-09c-metal.png
magick convert fh-09d-wood.png -compose copy -bordercolor transparent -border 5 temp/fh-09d-wood.png
magick convert fh-10a-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-10a-metal.png
magick convert fh-10b-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-10b-dungeon.png
magick convert fh-10c-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-10c-metal.png
magick convert fh-10d-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-10d-snow.png
magick convert fh-11a-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-11a-snow.png
magick convert fh-11b-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-11b-cave.png
magick convert fh-11c-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-11c-snow.png
magick convert fh-11d-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-11d-cave.png
magick convert fh-11e-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-11e-dungeon.png
magick convert fh-11f-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-11f-metal.png
magick convert fh-12a-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-12a-metal.png
magick convert fh-12b-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-12b-cave.png
magick convert fh-12c-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-12c-metal.png
magick convert fh-12d-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-12d-dungeon.png
magick convert fh-13a-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-13a-snow.png
magick convert fh-13b-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-13b-cave.png
magick convert fh-13c-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-13c-snow.png
magick convert fh-13d-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-13d-cave.png
magick convert fh-13e-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-13e-dungeon.png
magick convert fh-13f-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-13f-metal.png
magick convert fh-14a-wood.png -compose copy -bordercolor transparent -border 5 temp/fh-14a-wood.png
magick convert fh-14b-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-14b-cave.png
magick convert fh-15a-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-15a-snow.png
magick convert fh-15b-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-15b-cave.png
magick convert fh-15c-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-15c-dungeon.png
magick convert fh-15d-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-15d-metal.png
magick convert fh-16a-snow.png -compose copy -bordercolor transparent -border 5 temp/fh-16a-snow.png
magick convert fh-16b-cave.png -compose copy -bordercolor transparent -border 5 temp/fh-16b-cave.png
magick convert fh-16c-dungeon.png -compose copy -bordercolor transparent -border 5 temp/fh-16c-dungeon.png
magick convert fh-16d-metal.png -compose copy -bordercolor transparent -border 5 temp/fh-16d-metal.png